/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSearchRouteImport } from './routes/_site.search'
import { Route as SiteResetPasswordRouteImport } from './routes/_site.reset-password'
import { Route as SiteRegisterRouteImport } from './routes/_site.register'
import { Route as SiteOffersRouteImport } from './routes/_site.offers'
import { Route as SiteLoginRouteImport } from './routes/_site.login'
import { Route as SiteForgotPasswordRouteImport } from './routes/_site.forgot-password'
import { Route as SiteFavoritesRouteImport } from './routes/_site.favorites'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCarsRouteImport } from './routes/_site.cars'
import { Route as SiteAccountRouteImport } from './routes/_site.account'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteCarsCarIdRouteImport } from './routes/_site.cars.$carId'
import { Route as SiteBookingsBookingIdRouteImport } from './routes/_site.bookings.$bookingId'
import { Route as SiteBookingCarIdRouteImport } from './routes/_site.booking.$carId'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSearchRoute = SiteSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => SiteRoute,
} as any)
const SiteResetPasswordRoute = SiteResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRegisterRoute = SiteRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOffersRoute = SiteOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLoginRoute = SiteLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SiteRoute,
} as any)
const SiteForgotPasswordRoute = SiteForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFavoritesRoute = SiteFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCarsRoute = SiteCarsRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccountRoute = SiteAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCarsCarIdRoute = SiteCarsCarIdRouteImport.update({
  id: '/$carId',
  path: '/$carId',
  getParentRoute: () => SiteCarsRoute,
} as any)
const SiteBookingsBookingIdRoute = SiteBookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBookingCarIdRoute = SiteBookingCarIdRouteImport.update({
  id: '/booking/$carId',
  path: '/booking/$carId',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRoute
  '/cars': typeof SiteCarsRouteWithChildren
  '/contact': typeof SiteContactRoute
  '/favorites': typeof SiteFavoritesRoute
  '/forgot-password': typeof SiteForgotPasswordRoute
  '/login': typeof SiteLoginRoute
  '/offers': typeof SiteOffersRoute
  '/register': typeof SiteRegisterRoute
  '/reset-password': typeof SiteResetPasswordRoute
  '/search': typeof SiteSearchRoute
  '/booking/$carId': typeof SiteBookingCarIdRoute
  '/bookings/$bookingId': typeof SiteBookingsBookingIdRoute
  '/cars/$carId': typeof SiteCarsCarIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRoute
  '/cars': typeof SiteCarsRouteWithChildren
  '/contact': typeof SiteContactRoute
  '/favorites': typeof SiteFavoritesRoute
  '/forgot-password': typeof SiteForgotPasswordRoute
  '/login': typeof SiteLoginRoute
  '/offers': typeof SiteOffersRoute
  '/register': typeof SiteRegisterRoute
  '/reset-password': typeof SiteResetPasswordRoute
  '/search': typeof SiteSearchRoute
  '/': typeof SiteIndexRoute
  '/booking/$carId': typeof SiteBookingCarIdRoute
  '/bookings/$bookingId': typeof SiteBookingsBookingIdRoute
  '/cars/$carId': typeof SiteCarsCarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/account': typeof SiteAccountRoute
  '/_site/cars': typeof SiteCarsRouteWithChildren
  '/_site/contact': typeof SiteContactRoute
  '/_site/favorites': typeof SiteFavoritesRoute
  '/_site/forgot-password': typeof SiteForgotPasswordRoute
  '/_site/login': typeof SiteLoginRoute
  '/_site/offers': typeof SiteOffersRoute
  '/_site/register': typeof SiteRegisterRoute
  '/_site/reset-password': typeof SiteResetPasswordRoute
  '/_site/search': typeof SiteSearchRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/booking/$carId': typeof SiteBookingCarIdRoute
  '/_site/bookings/$bookingId': typeof SiteBookingsBookingIdRoute
  '/_site/cars/$carId': typeof SiteCarsCarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/cars'
    | '/contact'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/offers'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/booking/$carId'
    | '/bookings/$bookingId'
    | '/cars/$carId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/account'
    | '/cars'
    | '/contact'
    | '/favorites'
    | '/forgot-password'
    | '/login'
    | '/offers'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/'
    | '/booking/$carId'
    | '/bookings/$bookingId'
    | '/cars/$carId'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/account'
    | '/_site/cars'
    | '/_site/contact'
    | '/_site/favorites'
    | '/_site/forgot-password'
    | '/_site/login'
    | '/_site/offers'
    | '/_site/register'
    | '/_site/reset-password'
    | '/_site/search'
    | '/_site/'
    | '/_site/booking/$carId'
    | '/_site/bookings/$bookingId'
    | '/_site/cars/$carId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/search': {
      id: '/_site/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SiteSearchRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reset-password': {
      id: '/_site/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof SiteResetPasswordRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/register': {
      id: '/_site/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof SiteRegisterRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/offers': {
      id: '/_site/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof SiteOffersRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/login': {
      id: '/_site/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SiteLoginRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/forgot-password': {
      id: '/_site/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof SiteForgotPasswordRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/favorites': {
      id: '/_site/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof SiteFavoritesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cars': {
      id: '/_site/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof SiteCarsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/account': {
      id: '/_site/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof SiteAccountRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cars/$carId': {
      id: '/_site/cars/$carId'
      path: '/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof SiteCarsCarIdRouteImport
      parentRoute: typeof SiteCarsRoute
    }
    '/_site/bookings/$bookingId': {
      id: '/_site/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof SiteBookingsBookingIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/booking/$carId': {
      id: '/_site/booking/$carId'
      path: '/booking/$carId'
      fullPath: '/booking/$carId'
      preLoaderRoute: typeof SiteBookingCarIdRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteCarsRouteChildren {
  SiteCarsCarIdRoute: typeof SiteCarsCarIdRoute
}

const SiteCarsRouteChildren: SiteCarsRouteChildren = {
  SiteCarsCarIdRoute: SiteCarsCarIdRoute,
}

const SiteCarsRouteWithChildren = SiteCarsRoute._addFileChildren(
  SiteCarsRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAccountRoute: typeof SiteAccountRoute
  SiteCarsRoute: typeof SiteCarsRouteWithChildren
  SiteContactRoute: typeof SiteContactRoute
  SiteFavoritesRoute: typeof SiteFavoritesRoute
  SiteForgotPasswordRoute: typeof SiteForgotPasswordRoute
  SiteLoginRoute: typeof SiteLoginRoute
  SiteOffersRoute: typeof SiteOffersRoute
  SiteRegisterRoute: typeof SiteRegisterRoute
  SiteResetPasswordRoute: typeof SiteResetPasswordRoute
  SiteSearchRoute: typeof SiteSearchRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBookingCarIdRoute: typeof SiteBookingCarIdRoute
  SiteBookingsBookingIdRoute: typeof SiteBookingsBookingIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAccountRoute: SiteAccountRoute,
  SiteCarsRoute: SiteCarsRouteWithChildren,
  SiteContactRoute: SiteContactRoute,
  SiteFavoritesRoute: SiteFavoritesRoute,
  SiteForgotPasswordRoute: SiteForgotPasswordRoute,
  SiteLoginRoute: SiteLoginRoute,
  SiteOffersRoute: SiteOffersRoute,
  SiteRegisterRoute: SiteRegisterRoute,
  SiteResetPasswordRoute: SiteResetPasswordRoute,
  SiteSearchRoute: SiteSearchRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBookingCarIdRoute: SiteBookingCarIdRoute,
  SiteBookingsBookingIdRoute: SiteBookingsBookingIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
